### ISSUE TITLE
Connecting the module directly to a computer

### ISSUE THREAD

**Issue by dmitryk-nca** [makerdiary/nrf52840-m2#3]
Does the module implement some kind of standard M.2 device - i.e. can it be connected to M.2 slot on a PC and picked up by Linux as tty or storage device?

**Comment by caizelin** [comment]
@dmitryk-nca The nRF52840 M.2 Module is incompatible with the standard M.2 type as they have different signal definitions.
The typical application of this module is to integrate it into your custom embedded system.
